name: phpstan

on: [push, pull_request]

jobs:
    phpstan:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v6

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.4
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath
                    coverage: none

            -   name: Install dependencies
                run: composer update --prefer-dist --no-interaction

            -   name: Run PHPStan
                run: vendor/bin/phpstan analyse --no-progress
